### ISSUE TITLE
"Mustache evaluation error" on Heroku, but correct response while running on mac

### ISSUE THREAD

**Issue by abjurato** [PerfectlySoft/Perfect-Heroku-Buildpack-Example#1]
First of all, this example works totally correctly both on Heroku and locally on my mac, the issue is with my attempt to recreate this example myself from scratch.

I've added my own Hello.mustache file, changed makefile according to my .swift files and cp command for new mustache, in PerfectServerModuleInit() registered handler with same name as in mustache's handler pragma, in Xcode project's build settings added mustache to copy files list. On my mac everything works correctly.
But when I'm deploying app to Heroku (with Perfect's buildpack, and `web: perfectserverhttp --port $PORT` in Profile and scaled `heroku ps:scaled web=1`), strange things happen:

1.  for request to myappsname.herokuapp.com/Hello response is 
> 500 Mustache evaluation error No valid PageHandler was specified in the template's 
> pragmas.
as if I didn't register handler correctly. But why it works on my mac?

2. for request to myappsname.herokuapp.com/hello response is 
> The file "/hello" was not found.
as if requests are case-sensitive. But why in this example project it is not?

I understand that it is not an issue of this example project, but I've read totally everything on the Internet about Perfect (even translations from Chinese) and still can't get what am I doing wrong 🤔

**Comment by taplin** [comment]
so, I'd have to see the mustache file and PageHandler definition, but it seems possible that you're running into some issue with the fact that Linux is case sensitive.

**Comment by abjurato** [comment]
PerfectHandlers:
```
public func PerfectServerModuleInit() {
 
   PageHandlerRegistry.addPageHandler("Hello") {
        (r:WebResponse) -> PageHandler in
        return Hello()
    }

}
```


Hello.mustache:
```
{{% handler:Hello}}{{hello}}
```

Hello class:
```
class Hello: PageHandler {
    func valuesForResponse(context: MustacheEvaluationContext, collector: MustacheEvaluationOutputCollector) throws -> MustacheEvaluationContext.MapType {
    
        let val:MustacheEvaluationContext.MapType = ["hello":"hello"]
        return val
    }
}
```

And regarding case-sensivity: I've checked once again — TapTracker on Heroku becomes case-sensitive too. Can it be considered as a webserver's bug?

**Comment by abjurato** [comment]
Finally, was discovered that problem was that in another class in same .swift file was called one of PostgreSQL connector's methods, but PostgreSQL lib was not correctly described in makefile. So while adding PageHandlers on Heroku the application crashed or something like that.
