### ISSUE TITLE
[Question] How to avoid the deletion of the database after each deployment

### ISSUE THREAD

**Issue by darthpelo** [PerfectlySoft/Perfect-Heroku-Buildpack-Example#4]
Hi, I am trying to create new APIs based on the buildpack example, to understand better how Perfect works.
The only big issue that I have is that after each deploy on Heroku, the database is empty. This is strange because here:
https://github.com/PerfectlySoft/Perfect-Heroku-Buildpack-Example/blob/master/src/Tap%20Tracker%20Server/TTHandlers.swift#L42
the command is to create the  new table only if the database is empty.

How can I fix this problem?

**Comment by Sha0** [comment]
Good day.  Heroku deployments of any kind (Node.js, Ruby, PHP) do not persist data from previous deployments; each deployed system has a fresh environment.  The Heroku (or CloudFoundry) strategy is to have separate database services that your web services communicate with.  These database services should have persistent data.

**Comment by darthpelo** [comment]
Thanks for the clarification.
